=== RainGrd/crm/out/production/Xml-Demo/com/bdqn/demo/shopping.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT basket (meat+)>
<!--肉(部位,肉质,售价)-->
<!ELEMENT meat (part,quality,price)>
<!ELEMENT part ANY>
<!ELEMENT quality ANY>
<!ELEMENT price ANY>
<!--标识，品种，产地-->
<!ATTLIST meat
        id CDATA #IMPLIED
        varieties CDATA #IMPLIED
        Origin CDATA #REQUIRED
        >

=== RainGrd/crm/out/production/Xml-Demo/com/bdqn/demo/shopping.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--引入DTD-->
<!DOCTYPE basket SYSTEM "shopping.dtd">
<basket>
    <meat Origin="湖南宁乡" id="1" varieties="猪肉">
        <part>腿</part>
        <quality>上等</quality>
        <price>150.00</price>
    </meat>
    <meat Origin="内蒙古科尔沁草原" id="2" varieties="牛肉">
        <part>腿</part>
        <quality>上等</quality>
        <price>500.00</price>
    </meat>
</basket>
